theme: jekyll-theme-slate
title: Tastatura Dvorak pentru limba română
description: Implementare Dvorak cu diacritice corecte.
lang: ro
show_downloads: true
github:
  zip_url: https://github.com/thelightstain/tastatura-dvorak-romana/releases/download/v1.0.0/ro-dv-windows-1.0.0.zip
plugins:
  - jekyll-sitemap
